# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aelbouaa <aelbouaa@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/12/19 11:48:31 by aelbouaa          #+#    #+#              #
#    Updated: 2024/01/11 05:12:55 by aelbouaa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #



NAME = megaphone

CC = c++
FLAGS = -Wall -Wextra -Werror -std=c++98

SRCS = megaphone.cpp

all : $(NAME)

$(NAME) :
	$(CC) $(FLAGS) $(SRCS) -o $(NAME)


clean :
	rm -f $(NAME)

fclean :
	rm -f $(NAME)

re : fclean all